export const programContentDescription = [
  {
    title: 'Introdução',
    list: ['Historia da Dermopigmentação', 'Técnica Tebori', 'Dermográfo'],
  },
  {
    title: 'Anatomia e Fisiologia da Pele',
    list: [
      'Composição de cada Camada da Pele',
      'Diferença de Melanina entre Homens e Mulheres',
      'Sensores da Dor',
      'A Importância do Colágeno',
      'Reações Alérgicas',
      'Dermopigmentação sobre Cicatriz',
      'Quelóide',
      'Inflamação, Infecção e Necrose Tecidual',
      'Tinta Fixada no Organismo',
      'Pigmentação nas Regiões do Corpo',
      'Retoque de Dermopigmentação',
      'Quem pode fazer Dermopigmentação',
      'Problemas de Dermopigmentação nas Pernas e Pés',
      'Tipos de Estrias Brancas, Vermelhas e Cinzas ',
      'Profilaxia de Procedimento',
    ],
  },
  {
    title: 'Biossegurança',
    list: [
      'Vacina de Hepatite B e Tétano',
      'Limpeza Correta do Estúdio',
      'Ventilador na Sala de Procedimento',
      'Proibição do Glutaraldeido 2%',
      'Ácido Peracético e sua Aplicabilidade',
      'EPI’s (Equipamento de Segurança)',
      'Ultrasson',
      'Autoclave',
      'Teste Biológico para a Autoclave',
      'Assepsia da Pele',
      'Proibição da Estufa',
    ],
  },
  {
    title: 'Materiais para Dermopigmentação',
    list: [
      'Materiais Necessários',
      'Tamanhos e Utilização de Batoques',
      'Vaselina',
      'Gel de Ultrasson',
      'Manteigas de Cacau',
      'Materiais de Auxilio e Acalmante da Pele',
    ],
  },
  {
    title: 'Dermógrafo',
    list: [
      'Apresentação',
      'Maquina Rotativa',
      'Como Escolher a Melhor Máquina',
      'Funcionamento Correto da Máquina',
      'Montagem e Regulagem da Máquina',
      'Manutenção da Máquina',
    ],
  },
  {
    title: 'Agulhas',
    list: ['Agulhas: Espessura e Registro ANVISA', 'Traço', 'Agulhas Extras'],
  },
  {
    title: 'Biqueiras ou Ponteiras',
    list: ['Biqueiras Descartáveis'],
  },
  {
    title: 'Tintas/Pigmentos',
    list: [
      'Melhores Marcas',
      'Tintas Registradas pela ANVISA',
      'Preparo da Tinta',
      'Armazenamento da Tinta',
      'Tintas à Base de Água de Outros Solventes',
      'Tinta para Peles Negras',
      'Mistura de Tinta para Novos Tons',
    ],
  },
  {
    title: 'Sobrancelha',
    list: [
      'Fio a Fio: Técnica Básica, Tebori e com Demógrafo',
      'Sobrancelha Hiper-Realista ',
      'Esfumaçada',
      'Visagismo e Colorimetria',
    ],
  },
  {
    title: 'Cobertura de cicatriz',
    list: [
      'Tipos de Cicatriz ',
      'Avaliando a Melanina Local',
      'Mistura de Tinta',
      'Preenchimento Correto',
      'Cicatrizes na Cobertura',
    ],
  },
  {
    title: 'Cobertura de Estrias e Camuflagem',
    list: [
      'Tipos de Estrias',
      'Avaliando a Melanina Local',
      'Mistura de Tinta',
      'Tempo de Preenchimento',
      'Tipo de Agulha para o Procedimento',
      'Tempo de Retoque',
      'Qual Estria não é Aconselhável Cobrir',
      'Estimulação do Colágeno e Uso de Ácido',
      'Micromoxa (Exclusiva Angel’s Tattoo School)',
      'Camuflagem de Estria',
    ],
  },
  {
    title: 'Vitiligo',
    list: [
      'Tipos de Vitiligo',
      'Avaliando a Melanina Local',
      'Mistura de Tinta',
      'Tempo de Preenchimento',
      'Melhor Agulha para o Procedimento',
      'Tempo de Retoque',
      'Qual Vitiligo não é Aconselhável Cobrir',
    ],
  },
  {
    title: 'Delineador',
    list: [
      'Como Fazer',
      'Preenchimento Correto',
      'Avaliando a Melanina Local',
      'Tempo Retoque',
    ],
  },
  {
    title: 'Boca',
    list: [
      'Tipo de Preenchimento',
      'Aumento e Diminuição do Formato da Boca',
      'Mistura de Cores',
      'Tempo Retoque',
    ],
  },
  {
    title: 'Reconstrução de Auréola',
    list: [
      'Tipos de Auréola',
      'Melanina Local',
      'Mistura de Tinta',
      'Tempo de Preenchimento',
      'Melhor Tipo de Agulha',
      'Tempo de Retoque',
      'Cicatrização ',
      'Cuidados Especiais ',
      'Cicatrizes de Cirurgia e Procedimento Hipertrofico',
      'Modelos de Auréola',
      'Auréola Hiperrealistas ',
      'Auréola Masculina',
    ],
  },
  {
    title: 'Mudança do Formato da Auréola',
    list: [
      'Tipos de Auréola',
      'Melanina Local',
      'Mistura de Tinta ',
      'Tempo de Preenchimento',
      'Tipo de Agulha',
      'Tempo de Retoque',
      'Melhor Tamanho e Modelo',
    ],
  },
  {
    title: 'Dermopigmentação Capilar',
    list: [
      'Tipos de Cálvice',
      'Melanina Local',
      'Mistura de Tinta',
      'Tipos de Cabelo',
      'Melhor Tipo de Agulha',
      'Tempo de Retoque',
    ],
  },
  {
    title: 'Harmonização Facial e Técnica BBglow',
    list: ['Vitaminas', 'Colágeno', 'Tintas'],
  },
  {
    title: 'Valor do Procedimento',
    list: ['Como Calcular Valor?'],
  },
  {
    title: 'Normas e Leis',
    list: [
      'Proibição de Dermopigmentação para Menores',
      'Proibição de Utilização de Anestésicos',
      'Vigilância Sanitária e suas Normas',
      'Adequar do Espaço',
      'Ficha do Cliente',
    ],
  },
];
